### ISSUE TITLE
Automatically enable the plugin

### ISSUE THREAD

**Issue by SalmonGER** [jasonwynn10/SpawnInvis#2]
Hello!
Sorry, but this isn't a issue, it's more like a suggestion.
I really like this plugin and it works really well on my server. I just always need to type in /invis to activate the plugin after a restart. 

Can you add a feature to toggle it on automatically on server start?

**Comment by jasonwynn10** [comment]
there is a config file with that setting in it

**Comment by jasonwynn10** [comment]
https://github.com/jasonwynn10/SpawnInvis/releases/tag/v2.0.0 is the release link.

**Comment by SalmonGER** [comment]
Thanks! :D
